services:
        trading-backend:
                build: .
                container_name: alertsn7_v2_backend
                ports:
                        - "8077:8077"
                volumes:
                        # Persiste la base de datos SQLite fuera del contenedor
                        - sqlite_data:/app/data
                restart: unless-stopped

volumes:
        sqlite_data: